### PR TITLE
updated community slack link on the website

### PR DESCRIPTION
**Pull request by chinnaji**

### CODE REVIEW

**Review by eni4sure — CHANGES_REQUESTED** [review]
Can you change all the links to "https://linktr.ee/genztechies" instead

**Review by eni4sure — CHANGES_REQUESTED** [review]
Can you change all the links to "https://linktr.ee/genztechies" instead

**Comment by chinnaji** [comment]
Sure

**Comment by chinnaji** [comment]
It is done.

**Review by eni4sure — APPROVED** [review]
Awesome!

**Pull request merged**
